import Layout from '@/components/layout'
import React from 'react'

export default function privacyPolicy({ header, footer }) {

  const privacyPolicyData = `<h1 style="text-align: center;"><span style="color: rgb(0, 0, 0);">Privacy policy</span></h1>
  <h3><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Privacy Policy</span> </span></h3>
  <p><span style="color: rgb(0, 0, 0);">Last updated: April 6 2023 </span></p>
  <p><span style="color: rgb(0, 0, 0);">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. </span></p>
  <p><span style="color: rgb(0, 0, 0);">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. </span></p>
  <p>&nbsp;</p>
  <p><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Interpretation and Definitions</span> </span></p>
  <h4><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Interpretation</span> </span></h4>
  <p><span style="color: rgb(0, 0, 0);">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in the plural. </span></p>
  <h4>&nbsp;</h4>
  <h4><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Definitions</span> </span></h4>
  <p><span style="color: rgb(0, 0, 0);">For the purposes of this Privacy Policy: </span></p>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Account</span>&nbsp;means a unique account created for You to access our Service or parts of our Service. </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Company</span>&nbsp;(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Jamstack+, Pune, Maharashtra. </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Cookies</span>&nbsp;are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Country</span>&nbsp;refers to: Maharashtra, India </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Device</span>&nbsp;means any device that can access the Service such as a computer, a cellphone or a digital tablet. </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Personal Data</span>&nbsp;is any information that relates to an identified or identifiable individual. </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Service</span>&nbsp;refers to the Website. </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Service Provider</span>&nbsp;means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Usage Data</span>&nbsp;refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Website</span>&nbsp;refers to Jamstack+, accessible from jamstack.plus </span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">You</span>&nbsp;means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</span></li>
  </ul>
  <h2><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Collecting and Using Your Personal Data</span> </span></h2>
  <h3><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Types of Data Collected </span></span></h3>
  <h4><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Personal Data </span></span></h4>
  <p><span style="color: rgb(0, 0, 0);"><span data-token-index="0">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: </span></span></p>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Email address </span></span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span data-token-index="0">First name and last name </span></span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Phone number </span></span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Usage Data </span></span></li>
  </ul>
  <h4><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Usage Data </span></span></h4>
  <p><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Usage Data is collected automatically when using the Service. </span></span></p>
  <p><span style="color: rgb(0, 0, 0);"><span data-token-index="0">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. </span></span></p>
  <p><span style="color: rgb(0, 0, 0);">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</span></p>
  <p><span style="color: rgb(0, 0, 0);">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</span></p>
  <h4><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Tracking Technologies and Cookies</span> </span></h4>
  <p><span style="color: rgb(0, 0, 0);">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</span></p>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</span></li>
  </ul>
  <p><span style="color: rgb(0, 0, 0);">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.&nbsp;</span></p>
  <p><span style="color: rgb(0, 0, 0);">We use both Session and Persistent Cookies for the purposes set out below: </span></p>
  <h4><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Necessary / Essential Cookies</span> </span></h4>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Type: Session Cookies</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Administered by: Us</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Cookies Policy / Notice Acceptance Cookies</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Type: Persistent Cookies</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Administered by: Us</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</span></li>
  </ul>
  <h3><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Functionality Cookies</span> </span></h3>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Type: Persistent Cookies</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Administered by: Us</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</span></li>
  </ul>
  <p><span style="color: rgb(0, 0, 0);">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</span></p>
  <p>&nbsp;</p>
  <h2><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Use of Your Personal Data</span> </span></h2>
  <p><span style="color: rgb(0, 0, 0);">The Company may use Personal Data for the following purposes: </span></p>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>To manage Your Account:</strong>&nbsp;to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>For the performance of a contract:</strong>&nbsp;the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>To contact You:</strong>&nbsp;To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>To provide You</strong>&nbsp;with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>To manage Your requests:</strong>&nbsp;To attend and manage Your requests to Us.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>For business transfers:</strong>&nbsp;We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</span></li>
  </ul>
  <p><span style="color: rgb(0, 0, 0);">We may share Your personal information in the following situations: </span></p>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>With Service Providers:</strong>&nbsp;We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>For business transfers:</strong>&nbsp;We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>With Affiliates:</strong>&nbsp;We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>With business partners:</strong>&nbsp;We may share Your information with Our business partners to offer You certain products, services or promotions.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>With other users:</strong>&nbsp;when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);"><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</span></li>
  </ul>
  <h3><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Retention of Your Personal Data</span> </span></h3>
  <p><span style="color: rgb(0, 0, 0);">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</span></p>
  <p><span style="color: rgb(0, 0, 0);">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</span></p>
  <p>&nbsp;</p>
  <h3><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Transfer of Your Personal Data</span> </span></h3>
  <p><span style="color: rgb(0, 0, 0);">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to &mdash; and maintained on &mdash; computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</span></p>
  <p><span style="color: rgb(0, 0, 0);">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</span></p>
  <p><span style="color: rgb(0, 0, 0);">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</span></p>
  <p>&nbsp;</p>
  <h3><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Delete Your Personal Data</span> </span></h3>
  <p><span style="color: rgb(0, 0, 0);">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</span></p>
  <p><span style="color: rgb(0, 0, 0);">Our Service may give You the ability to delete certain information about You from within the Service.</span></p>
  <p><span style="color: rgb(0, 0, 0);">You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</span></p>
  <p><span style="color: rgb(0, 0, 0);">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</span></p>
  <h2><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Disclosure of Your Personal Data</span> </span></h2>
  <h3><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Business Transactions</span> </span></h3>
  <p><span style="color: rgb(0, 0, 0);">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.&nbsp;</span></p>
  <h3><span style="color: rgb(0, 0, 0);"><span data-token-index="0"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Law enforcement</span> </span></span></h3>
  <p><span style="color: rgb(0, 0, 0);"><span data-token-index="0"><span class="notion-enable-hover" data-token-index="0">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency). </span></span></span></p>
  <h3><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Other legal requirements</span> </span></h3>
  <p><span style="color: rgb(0, 0, 0);">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</span></p>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Comply with a legal obligation</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Protect and defend the rights or property of the Company</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Prevent or investigate possible wrongdoing in connection with the Service</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Protect the personal safety of Users of the Service or the public</span></li>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">Protect against legal liability</span></li>
  </ul>
  <h3><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Security of Your Personal Data</span> </span></h3>
  <p><span style="color: rgb(0, 0, 0);"><span data-token-index="0">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security. </span></span></p>
  <h2><span style="color: rgb(0, 0, 0);"><span data-token-index="0"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Children's Privacy</span> </span></span></h2>
  <p><span style="color: rgb(0, 0, 0);">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</span></p>
  <p><span style="color: rgb(0, 0, 0);">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</span></p>
  <h2><span style="color: rgb(0, 0, 0);"><span class="notion-enable-hover" style="font-weight: 600;" data-token-index="0">Links to Other Websites</span> </span></h2>
  <p><span style="color: rgb(0, 0, 0);">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</span></p>
  <p><span style="color: rgb(0, 0, 0);">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span></p>
  <h2><span style="color: rgb(0, 0, 0);"><strong>Changes to this Privacy Policy</strong></span></h2>
  <p><span style="color: rgb(0, 0, 0);">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</span></p>
  <p><span style="color: rgb(0, 0, 0);">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</span></p>
  <p><span style="color: rgb(0, 0, 0);">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span></p>
  <h2><span style="color: rgb(0, 0, 0);"><strong>Contact Us</strong></span></h2>
  <p><span style="color: rgb(0, 0, 0);">If you have any questions about this Privacy Policy, You can contact us:</span></p>
  <ul>
  <li style="color: rgb(0, 0, 0);"><span style="color: rgb(0, 0, 0);">By email:&nbsp;hello@jamstack.plus</span></li>
  </ul>
  <p>&nbsp;</p>
  <p>&nbsp;</p>`;


  return (
    <Layout header={header} footer={footer}>
      <div className='container mx-auto'>
          <div dangerouslySetInnerHTML={{__html:`${privacyPolicyData}`}}></div>
      </div>
    </Layout>
  )
}

